### ISSUE TITLE
Wanpppconn1 not working

### ISSUE THREAD

**Issue by bluesky81** [chstorb/Fritz#1]
Hi,
I got a SocketException (Unable to connect because the destination computer refused to connection) wenn I try this:

Dim service As New Wanpppconn1("https://fritz.box")
service.SoapHttpClientProtocol.Credentials = New NetworkCredential("User", "Password")
service.GetExternalIPAddress(ip)

What could be wrong???

**Comment by inflames2k** [comment]
Try the WANIPConnection Service. Depending on the Internet Connection Type the corresponding Service is Not Working.

**Comment by PatrickSchmidtSE** [comment]
I agree with @inflames2k , but  am i missing something? There is no service class implemented for WANIPConnection.

**Comment by chstorb** [comment]
Sorry for the very late reply. "SearchForTheCode" is right, WANIPConnection is not yet implemented in this library.
